# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GMIMG
author: Jimin Hwang
email: gming7281@gmail.com
description: >-
  Mechagrammer
introduction: >-
  Hello. I'm Seoultech univesity student in South Korea.
  My english is so terrible but trying ;)
  I'm majoring in mechanical engineering system. and my minor is computer engineering.
  I am dreaming to be a good developer.
  This blog is writing that today I learned.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: None
#facebook_username: 
github_username:  GMIMG
disqus:
  shortname: GMIMG

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
#  - jekyll-last-modified-at
exclude:
   - Gemfile
   - Gemfile.lock

#timezone: Asia/Seoul
permalink: /posts/:title
paginate: 10
paginate_path: "/posts/:num/"
category_dir: category/
tag_dir: tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author: Gmimg
      layout: post
      category: None
      search: true #false
      comments: true #false
      toc: true
      sidebar:
        nav: "main"

  - scope:
      path: "page"
      type: 
    values:
      sidebar:
        nav: "main"