#Basic setting
title: GMIMG
author: Jimin Hwang
email: gming7281@gmail.com
description: Mechagrammer
introduction: >-
  Hello. I'm Seoultech univesity student in South Korea.
  My english is so terrible but trying ;)
  I'm majoring in mechanical engineering system. and my minor is computer engineering.
  I am dreaming to be a good developer.
  This blog is writing that today I learned.
baseurl: ""
url: ""
#twitter_username: 
#facebook_username: 
#instagram_username:
github_username: GMIMG
disqus:
  shortname: GMIMG
rss: Subscribe
markdown: kramdown
mathjax : true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
lang: ko
permalink: /posts/:title
paginate: 5
paginate_path: "/posts/:num/"
category_dir: category/
tag_dir: tag/
algolia:
  application_id: XOU4HIXAXB
  index_name:     blog # You can replace that with whatever name you want
  search_only_api_key    : 2cefbb1667552724a06f3051447863bc # YOUR_SEARCH_ONLY_API_KEY

#폴더에 있는 파일의 YAML디폴트값
defaults:
  # _posts
  - scope:
      path: ""
      type: posts #_posts폴더안에있으면
    values:
      author: Gmimg
      layout: post
      search: true #false
      comments: true #false
      #toc: true #목차
      #category: None
      notice: false
      
  # page
  - scope:
      path: "page" #page폴더 안에있는 html
      type: 
    values:
      sidebar: "main"




# _data
# 사이트 전반에 대한 데이터
# navigation.yml : 포스트의 카테고리를 관리하는 YAML (최대 두단계의 자손 카테고리까지 가능)

# _includes
# disqus.html : disqus(댓글서비스)에서 제공하는 형식

# _layouts
# 페이지들의 layout을 설정, Liquid 템플릿 언어 사용.
# defalt.html : {YAML(page.lang,site.lang),script(masthjax,discus),include(head,header,footer)}
# page.html : {layout(defalut),YAML(page.sidebar),include(sidebar)}
# post.html : {layout(page),YAML(page.toc,site.disqus.shortname,)include(post-header,toc,disqus)}

# _posts {layout(post)}
# 포스트를 저장하는곳 (카테고리별로 폴더별로 묶어서 저장하면 관리하기 편함)

# _sass
# 사이트 전반의 SCSS 전처리기 저장소
# 0-plugins : 웹상에 배포된 플러그인 저장
# 1-base :  
# 2-layout :
# 3-expo :
# gmimg.scss : 폴더관리

# _site
# jekyll local서버 컴파일(?)

# assets
# 포스팅에 필요한 이미지 및 기타 애셋

# page
# 사이트 페이지의 구성
