title: GMIMG
author: Jimin Hwang
email: gming7281@gmail.com
description: Mechagrammer
introduction: >-
  Hello. I'm Seoultech univesity student in South Korea.
  My english is so terrible but trying ;)
  I'm majoring in mechanical engineering system. and my minor is computer engineering.
  I am dreaming to be a good developer.
  This blog is writing that today I learned.
baseurl: ""
url: ""
#twitter_username: 
#facebook_username: 
github_username: GMIMG
disqus:
  shortname: GMIMG
rss: Subscribe
markdown: kramdown
mathjax : true
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
lang: ko_KR
permalink: /posts/:title
paginate: 15
paginate_path: "/posts/:num/"
category_dir: category/
tag_dir: tag/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author: Gmimg
      layout: post
      search: true #false
      comments: true #false
      toc: true
      #category: None
      
  # _page
  - scope:
      path: "page"
      type: 
    values:
      sidebar: "main"